version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  node:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - PORT=3000
      - DB='index.sqlite'
      - OWNER='owner.json'
