version: '3.9'

services:
  node-1:
    build: .
    ports:
      - '3000:3000'
    environment:
      - CLIENT_PORT=3000
      - HOST=localhost
      - PROXY_HOST=host.docker.internal
      - PROXY_PORT=5001
      - DATABASE_PATH='index.sqlite'
      - OWNER_PATH='owner.json'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  node-2:
    build: .
    ports:
      - '3001:3000'
    environment:
      - CLIENT_PORT=3000
      - HOST=localhost
      - PROXY_HOST=host.docker.internal
      - PROXY_PORT=5001
      - DATABASE_PATH='index.sqlite'
      - OWNER_PATH='owner.json'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  node-3:
    build: .
    ports:
      - '3002:3000'
    environment:
      - CLIENT_PORT=3000
      - HOST=localhost
      - PROXY_HOST=host.docker.internal
      - PROXY_PORT=5001
      - DATABASE_PATH='index.sqlite'
      - OWNER_PATH='owner.json'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
