version: '3.9'

services:
  node:
    build: .
    ports:
      - '${HTTP_SERVICE_PORT}:${HTTP_SERVICE_PORT}'
    environment:
      - CLIENT_PORT=${HTTP_SERVICE_PORT}
      - HOST=${HTTP_SERVICE_PORT}
      - PROXY_HOST=${PROXY_SERVICE_HOST}
      - PROXY_PORT=${PROXY_SERVICE_PORT}
      - DATABASE_PATH=${DATABASE_PATH}
      - OWNER_PATH=${OWNER_PATH}
    volumes:
      - './temp:/node/temp'
