version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  node:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - CLIENT_PORT=3000
      - SERVER_PORT=1907
      - HOST_IP=localhost
      - PROXY_HOST=host.docker.internal
      - PROXY_PORT=5000
      - DB='index.sqlite'
      - OWNER='owner.json'
    extra_hosts:
      - "host.docker.internal:host-gateway"
