export const BLOCK_CHAIN_INSTANCE = 'BLOCK_CHAIN_INSTANCE';
export const OWNER_INSTANCE = 'OWNER_INSTANCE';
export const CREATE_USER_INSTANCE = 'CREATE_USER_INSTANCE';
export const ABORT_CONTROLLER = 'ABORT_CONTROLLER';
export const GLOBAL_BLOCK = 'GLOBAL_BLOCK';
export const CREATE_TRANSACTION_INSTANCE = 'CREATE_TRANSACTION_INSTANCE';
export const CREATE_BLOCK_INSTANCE = 'CREATE_BLOCK_INSTANCE';
export const LOAD_USER_INSTANCE = 'LOAD_USER_INSTANCE';
